### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by mdd45** [razor85/FenrirScreenshotManager#1]
Hello and thank you for your efforts in this manager. I'm using windows 10 and having installed python 3.9 64b while trying to boot the .py i'm getting this error:

 C:\Users\*>C:\Users\*\Downloads\FenrirScreenshotManager-main\FenrirScreenshotManager-main\fenrirScreenshotManager.py
Traceback (most recent call last):
  File "C:\Users\*\Downloads\FenrirScreenshotManager-main\FenrirScreenshotManager-main\fenrirScreenshotManager.py", line 1, in <module>
    from PyQt5.QtWidgets import (QApplication,
ModuleNotFoundError: No module named 'PyQt5'

Any idea why this is happening?

**Comment by razor85** [comment]
Hello, you're welcome :) Hope the app is useful. Looks like you are missing Qt5.

Open up a terminal and type (you are probably missing Pillow too):
`python -m pip install PyQt5 Pillow`

Btw there is a ready to use executable in the releases page. Cheers!

**Comment by mdd45** [comment]
.exe works fine, still cannot get the .py to boot. Thanks for the help

**Comment by razor85** [comment]
I'm glad the .exe works, what's the problem with the .py now?

**Comment by mdd45** [comment]
I've installed python from windows store and then installed pillow using the above command but still getting the error: 

"C:\Users\****\Downloads\FenrirScreenshotManager-main\fenrirScreenshotManager.py", line 1, in <module>
    from PyQt5.QtWidgets import (QApplication,
ModuleNotFoundError: No module named 'PyQt5'

**Comment by razor85** [comment]
Weird, you should have got PyQt5 as well, try:

python -m pip install PyQt5
python -m pip install Pillow
python -m pip install requests

those 3 should give you everything you need.
Also make sure you are using Python 3. I never installed python from the windows store, I'm always using the installer from python.org

**Comment by mdd45** [comment]
After uninstalling and reinstalling python-3.9.6-amd64.exe and running all the above command lines now it boots fine. Thank you for the support.
