### ISSUE TITLE
Batch Download Function possibility?

### ISSUE THREAD

**Issue by regulardude400** [razor85/FenrirScreenshotManager#3]
Hi I just want to say thanks for creating this tool.  Is there any chance that this could receive a batch download function similar to OPL manager found here: https://www.psx-place.com/resources/opl-manager-tool-to-manage-your-games.663/ ?  This would be extremely useful to the "heavy" users of this tool. :)

Edit:  I found an art image pack online for the covers.  google for emumovies and search sega saturn 2d boxes pack.

**Comment by razor85** [comment]
Hi, sorry for the long time (I'm quite busy nowadays). Are you still interested in that?

**Comment by regulardude400** [comment]
Hey no worries razor85. I was just needing covers for like 150 games and didn't want to manually download them for each game. But since I found the covers, you don't have to add it unless you want to. :) Thank you.
