### ISSUE TITLE
Blank screen on cover search

### ISSUE THREAD

**Issue by mydok** [razor85/FenrirScreenshotManager#7]
No results or image on cover search after pressing replace button.

Tested in 0.2 and 0.3 release and also cloning git repo

![image](https://github.com/razor85/FenrirScreenshotManager/assets/4757651/342d09d2-bc85-4268-8ff2-6bb8fbeacb2c)

**Comment by PJSOConnell** [comment]
Hey @razor85 - I have a fix for this that I can push if you like.

**Comment by razor85** [comment]
Cool, send a PR please. I have no time to maintain that :(
